### ISSUE TITLE
BNS names "disappear" during re-orgs

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain-api#614] opened 2021-05-27 08:44 UTC
When a name is registered or updated, it has a boolean flag `latest` set to `true`. The purpose of this flag is to allow fast enumeration of lists of names given various filtering criteria. Without the `latest` flag, then endpoints like `/v1/namespaces/{tld}/names` would have to perform an inefficient recursive JOIN to identify the latest status for each possible name it could return. The `namespaces`, `names`, and `subdomains` tables all use this `latest` flag. 

However, there's a bug in the re-org handling where `latest` is never updated during forks. This leads to situations where the _actual_ latest canonical name is flagged as `latest=false`, and all queries filter it out. 

This just happened with the name `aulneau.stx`. See the SQL output below showing re-org contention at block 16415. The row with `id=1803` eventually "won", according to the stacks-node, as being part of the canonical block. While row `id=1802` has been orphaned. The out-of-date `latest` flag is also visible. So now requests to `/v1/names/aulneau.stx` and similar endpoints will return empty.

```json
[
  {
    "id": 1803,
    "name": "aulneau.stx",
    "address": "SP3N4FPBG1PXMKEW0Y4K2MCSWDXHZP42YV5YW3AY4",
    "registered_at": 16415,
    "zonefile_hash": "f1df7f6ea05a3e6de952bb393429a5048acc61ca",
    "zonefile": "",
    "namespace_id": "stx",
    "latest": true,
    "status": "name-register",
    "canonical": false,
    "atch_resolved": false
  },
  {
    "id": 1802,
    "name": "aulneau.stx",
    "address": "SP3N4FPBG1PXMKEW0Y4K2MCSWDXHZP42YV5YW3AY4",
    "registered_at": 16415,
    "zonefile_hash": "f1df7f6ea05a3e6de952bb393429a5048acc61ca",
    "zonefile": "$ORIGIN aulneau.stx\n$TTL 3600\n_http._tcp\tIN\tURI\t10\t1\t\"https://gaia.blockstack.org/hub/1QEin7SMRVDopWnXoL7dqob94cCNzeNm5M/profile.json",
    "namespace_id": "stx",
    "latest": false,
    "status": "name-register",
    "canonical": true,
    "atch_resolved": true
  }
]
```

The fix is straight forward:
1. When any of the BNS table rows are marked as `canonical=true` or `canonical=false` during re-org, a second pass must be made to re-identify the the latest names, and set the `latest` flag as well. That code should happen around here: https://github.com/blockstack/stacks-blockchain-api/blob/cba848585f2d372345aca9a35ae984b5dd7ab6d3/src/datastore/postgres-store.ts#L818-L858
For example:
```sql
UPDATE names 
SET canonical = $2
WHERE index_block_hash = $1 AND canonical != $2
RETURNING name
```
Then for each returned `name`, run a query that identifies the last `canonical=true` name with the highest block_height and set it to `latest=true`, and set others to `latest=false`. This should be possible with a single query per name using a CTE.

2. Looking at the above SQL results for `aulneau.stx`, it's clear that `zonefile` content should be stored as relational data in a separate table. The BNS related queries can do a simple JOIN against that table using the `zonefile_hash` to retrieve the content.

**Comment by aulneau** [comment] 2021-05-27 12:36
cc @andresgalante for visibility.

This bug will create issues in the extension and any app wanting to use names.

**Comment by diwakergupta** [comment] 2021-05-27 13:37
@asimm241 could you or @noumanahmad001 take this on?

**Comment by asimm241** [comment] 2021-05-27 19:29
sure !

**Comment by HariniRajan397** [comment] 2021-06-02 13:07
Hi, We have a similar name "disappearing" issue reported by one of our users of BlockSurvey. This user has been using BlockSurvey for one month and suddenly we couldn't find his name. Because of this, authentication fails in Stacks.js as the coreApiUrl call verification to find the id comes as null. 

His id is "nomadcarl.id.blockstack". I couldn't find this name anywhere.

I tried finding the names in https://core.blockstack.org/v1/names/nomadcarl.id.blockstack  and https://stacks-node-api.mainnet.stacks.co/v1/names/nomadcarl.id.blockstack . But I am getting a "404".  I also noticed both the calls are redirected to registrar.blockstack.org. 

I am wondering, will this behaviour be similar to this issue. If not, need some help in finding the root cause for this issue.  Kindly let me know your thoughts on the same. Thank you so much.  cc : @markmhx

**Comment by asimm241** [comment] 2021-06-02 13:20
> Hi, We have a similar name "disappearing" issue reported by one of our users of BlockSurvey. This user has been using BlockSurvey for one month and suddenly we couldn't find his name. Because of this, authentication fails in Stacks.js as the coreApiUrl call verification to find the id comes as null.
> 
> His id is "nomadcarl.id.blockstack". I couldn't find this name anywhere.
> 
> I tried finding the names in https://core.blockstack.org/v1/names/nomadcarl.id.blockstack and https://stacks-node-api.mainnet.stacks.co/v1/names/nomadcarl.id.blockstack . But I am getting a "404". I also noticed both the calls are redirected to registrar.blockstack.org.
> 
> I am wondering, will this behaviour be similar to this issue. If not, need some help in finding the root cause for this issue. Kindly let me know your thoughts on the same. Thank you so much. cc : @markmhx

Yes! Seems like this behaviour is also because of name re-orgs.
I have created the PR for #620. It should be merged after the review by @zone117x. 
Also, @zone117x do we have to write some scripts to redeem broken names?

**Closed** 2021-07-20 15:26 UTC
Labels: BNS, bug
