### ISSUE TITLE
Multisig details in tx payload

### ISSUE THREAD

**Issue by agraebe** [blockstack/stacks-blockchain-api#305] opened 2020-10-22 16:38 UTC
While multi-signature transactions are supported in the core and inside our tooling, the API doesn't return multi-sig details. Most importantly, this should include the list of addresses that own the transaction.

I wonder if timestamps for signing are relevant (but not important), too?

**Comment by zone117x** [comment] 2021-03-05 09:35
Dupe of https://github.com/blockstack/stacks-blockchain-api/issues/200

**Closed by zone117x** 2021-03-05 09:35 UTC
Labels: enhancement, help wanted
