### ISSUE TITLE
Stacks Wallet: 'transaction rejected'

### ISSUE THREAD

**Issue by joshmatix** [blockstack/stacks-blockchain-api#485] opened 2021-03-11 09:49 UTC
Running Mint on VirtualBox
Trying to transfer 190 STX from stacks wallet.
The wallet has about  200 STX undelegated.
{
  "error": "transaction rejected",
  "reason": "NotEnoughFunds",
  "reason_data": {
    "actual": "0x00000000000000000000000005f56aa0",
    "expected": "0x0000000000000000000000000b532c34"
  },
  "txid": "c6997b67144f3093e40ecf99d7f90df6d947359dff48f721e5c79861cd4dcf67"
}

STX Addr: SP2H0DVKACPTJV3A5ERQ9MQ9MVZSRR0ZQHWFJDGC2

![image](https://user-images.githubusercontent.com/473381/110768271-13a65200-8225-11eb-93df-08405e18153c.png)

**Comment by psq** [comment] 2021-03-12 01:48
please note that at the time, `/v2/accounts/...` reported 0x00000000000000000000000005f56aa0, so the api value using the other balance endpoint is incorrect (the real issue here), and the transaction fails as expected given the actual balance

**Comment by zone117x** [comment] 2021-03-12 09:25
This is caused by the bug here: https://github.com/blockstack/stacks-blockchain-api/issues/390

And is fixed in this PR https://github.com/blockstack/stacks-blockchain-api/pull/489

The aborted tx causing the balance bug for this address is
https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/0xe3813e37ee30842fc27b7d82d1bbc1e3bf8ccff1e0ab4a2eda1951e1c758038c

**Closed** 2021-03-12 09:30 UTC
