### ISSUE TITLE
ConflictingNonceInMempool error thrown by faucet

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-blockchain-api#372] opened 2020-12-22 21:19 UTC
Using `ST2F02DZ6KFSFYRP4BB0B6N8YW33VVBEN4FP0WVDP` with https://www.blockstack.org/testnet/faucet

> {"error":"Error: Response 400: Bad Request fetching http://stacks-node-follower.prod-xenon.svc.cluster.local:20443/v2/transactions - {\"error\":\"transaction rejected\",\"reason\":\"ConflictingNonceInMempool\",\"txid\":\"c317af3fa1e6929ac5086493fa7c2590466e67e6a61bb5180c84ec84b2104041\"}","stack":"Error: Response 400: Bad Request fetching http://stacks-node-follower.prod-xenon.svc.cluster.local:20443/v2/transactions - {\"error\":\"transaction rejected\",\"reason\":\"ConflictingNonceInMempool\",\"txid\":\"c317af3fa1e6929ac5086493fa7c2590466e67e6a61bb5180c84ec84b2104041\"}\n    at StacksCoreRpcClient.fetchText (/app/lib/core-rpc/client.js:72:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async StacksCoreRpcClient.fetchJson (/app/lib/core-rpc/client.js:51:30)\n    at async StacksCoreRpcClient.sendTransaction (/app/lib/core-rpc/client.js:107:24)\n    at async /app/lib/api/routes/faucets.js:140:42\n    at async run (/app/node_modules/p-queue/dist/index.js:159:29)","errorTag":"d1600224-5c28-4c3c-bac6-d42651c193f1"}

**Comment by diwakergupta** [comment] 2020-12-22 21:25
When I attempt to hit the faucet endpoint directly, I get two different errors on successive attempts:

```
$ curl -X POST "https://stacks-node-api.krypton.blockstack.org/extended/v1/faucets/stx?address=ST2F02DZ6KFSFYRP4BB0B6N8YW33VVBEN4FP0WVDP"
{"error":"FetchError: request to http://stacks-node-miner.prod-krypton.svc.cluster.local:20443/v2/fees/transfer failed, reason: socket hang up","stack":"FetchError: request to http://stacks-node-miner.prod-krypton.svc.cluster.local:20443/v2/fees/transfer failed, reason: socket hang up\n    at ClientRequest.<anonymous> (/app/node_modules/cross-fetch/node_modules/node-fetch/lib/index.js:1461:11)\n    at ClientRequest.emit (events.js:315:20)\n    at Socket.socketOnEnd (_http_client.js:493:9)\n    at Socket.emit (events.js:327:22)\n    at endReadableNT (_stream_readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","errorTag":"ac988089-9a02-41cc-aaf4-1fbe76640617"}

$ curl -X POST "https://stacks-node-api.krypton.blockstack.org/extended/v1/faucets/stx?address=ST2F02DZ6KFSFYRP4BB0B6N8YW33VVBEN4FP0WVDP"

{"error":"FetchError: request to http://stacks-node-miner.prod-krypton.svc.cluster.local:20443/v2/transactions failed, reason: socket hang up","stack":"FetchError: request to http://stacks-node-miner.prod-krypton.svc.cluster.local:20443/v2/transactions failed, reason: socket hang up\n    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1455:11)\n    at ClientRequest.emit (events.js:315:20)\n    at Socket.socketOnEnd (_http_client.js:493:9)\n    at Socket.emit (events.js:327:22)\n    at endReadableNT (_stream_readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","errorTag":"f334b511-8c5e-4d93-b4dd-98507f928238"}
```

Note that they fail at different endpoints on the miner (`v2/fees/transfer` vs. `v2/transactions`) but both times with "reason: socket hang up". Unfortunately I see nothing about these requests in the API logs.

**Comment by diwakergupta** [comment] 2020-12-22 21:31
Also, I don't see txid `c317af3fa1e6929ac5086493fa7c2590466e67e6a61bb5180c84ec84b2104041` or `8ddbb46b683b2cb2bcfa937ecdbea5cde8a60c952f6793f3436f261032d16c32` (from a previous attempt by @markmhx ) anywhere in either the miner or follower logs.

**Comment by diwakergupta** [comment] 2020-12-22 21:40
Interestingly, if I request STX to that address from the faucet page, I get back the exact same txid that Mark got. Is this expected?

```
"{"error":"Error: Response 400: Bad Request fetching http://stacks-node-follower.prod-xenon.svc.cluster.local:20443/v2/transactions - {\"error\":\"transaction rejected\",\"reason\":\"ConflictingNonceInMempool\",\"txid\":\"c317af3fa1e6929ac5086493fa7c2590466e67e6a61bb5180c84ec84b2104041\"}","stack":"Error: Response 400: Bad Request fetching http://stacks-node-follower.prod-xenon.svc.cluster.local:20443/v2/transactions - {\"error\":\"transaction rejected\",\"reason\":\"ConflictingNonceInMempool\",\"txid\":\"c317af3fa1e6929ac5086493fa7c2590466e67e6a61bb5180c84ec84b2104041\"}\n    at StacksCoreRpcClient.fetchText (/app/lib/core-rpc/client.js:72:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async StacksCoreRpcClient.fetchJson (/app/lib/core-rpc/client.js:51:30)\n    at async StacksCoreRpcClient.sendTransaction (/app/lib/core-rpc/client.js:107:24)\n    at async /app/lib/api/routes/faucets.js:140:42\n    at async run (/app/node_modules/p-queue/dist/index.js:159:29)","errorTag":"71cc6703-59fb-4933-9849-2e1fdacd7001"}"
```

Again, no mention of this txid or ConflictingNonceInMempool in either the miner or follower logs.

**Comment by diwakergupta** [comment] 2020-12-22 21:45
Related issue https://github.com/blockstack/stacks-blockchain/issues/2144

**Comment by kantai** [comment] 2020-12-22 22:17
This issue was caused by downtime in the Xenon testnet miner -- the follower had a more recent view of the chainstate at this point, so accepted txid `0x9f650ab0a8f80967c95fcb6df43aec5257d8f385061f2adedeba458de931614d`, but this txid was rejected by the miner (because the miner didn't have a recent view of the chain that would validate this txid). Because of this, the miner never received the txid, and the tx never got processed. The faucet could avoid this issue if it increased its tx fee when getting a ConflictingNonceInMempool error, to replace the previous transaction.

This is ultimately related to the lack of an anti-entropy protocol in the stacks-node's mempool -- if a transaction isn't accepted when first broadcast, there's no protocol for retrying. Users can get around this by manually pushing the transaction to a miner's mempool themselves.

**Comment by markmhx** [comment] 2020-12-22 22:53
> The faucet could avoid this issue if it increased its tx fee when getting a ConflictingNonceInMempool error, to replace the previous transaction.

It'd be great if the Blockchain API could handle this automatically for the user and client.

**Comment by kantai** [comment] 2020-12-23 01:39
I don't think it could -- increasing the TX fee requires re-signing the transaction.

**Comment by diwakergupta** [comment] 2020-12-23 02:52
I think we can close this and perhaps even #371 in favor of #359?

We're already tracking the anti-entropy protocol for mempool on the blockchain end in blockstack/stacks-blockchain#2193

**Closed** 2021-02-15 14:44 UTC
