### ISSUE TITLE
Reduce amount path metrics for addresses/tx's

### ISSUE THREAD

**Issue by wileyj** [blockstack/stacks-blockchain-api#403] opened 2021-01-19 01:35 UTC
**Describe the bug**
Metrics for the API are getting  out of hand in the returned data for prometheus. 

We have too many data points like this:
`http_request_duration_seconds_count{method="get",path="/extended/v1/address/<address>/transactions",status_code="200"} 2`
Currently, we're getting ts data point for *every* path. this means there could be 100's of 1000's (i stopped waiting after 15s). 

We had a similar issue with the legacy explorer that was handled like this:
https://github.com/blockstack/blockstack-explorer/blob/master/server/index.js#L24-L37

**Expected behavior**
metrics are returned quickly

**Comment by zone117x** [comment] 2021-01-19 13:21
Yikes. The drastic resource usage caused by out-of-the-box usage of this lib makes me inclined to drop it all together. 

The referenced fixed in the legacy explorer would require hard coding in several paths (probably 10s), and add another layer of API endpoints to manually maintain against the source of truth.

The lib's [readme](https://github.com/tdeekens/promster) fails to mention any performance/resource usage considerations when used in a production app. It's also not as popular as I'd expect. 

Can we go over the metrics we are wanting to expose, and work from there?

**Comment by wileyj** [comment] 2021-01-19 15:32
sure. i don't think it's necessarily a problem with the lib, it's more because of the nature of the application itself where we have many many different endpoints we're telling it to track. 

i'll have to look around and reply back with site metrics we would like to have. system metrics we still want to keep though: cpu/memory etc

**Comment by wileyj** [comment] 2021-01-19 16:51
Here's a generic set of metrics that are incredibly useful (from the legacy explorer). 
the nodejs gc metrics, we don't currently use other than checking it against the memory profile. 
the http metrics though, are more important. they can help us determine how long requests take, and from there determine if we're overloaded etc. 

It also helps us check how many 404's we're getting (like in the case of being scraped/crawled). 

[metrics.txt](https://github.com/blockstack/stacks-blockchain-api/files/5837333/metrics.txt)

**Comment by zone117x** [comment] 2021-01-19 17:00
The API surface isn't all that big, it sounds like the lib is failing to respect the Express defined url parameters. So things like `/get_something/:address` cause it to track a "new endpoint" for each `:address` parameter. The fix in the legacy explorer appears to be manually stripping out these url parameters, which I'd definitely like to avoid manually mapping and maintaining. 

If this "batteries included" express-prom lib has poor default behaviors, might be worth adding a "dumb" prometheus lib that doesn't require hacky behavioral overrides.

**Comment by wileyj** [comment] 2021-01-19 18:49
Using a "dumb" lib isn't a concern from my end. 
https://github.com/siimon/prom-client is the lib linked from prom docs( https://prometheus.io/docs/instrumenting/clientlibs/ )

**Comment by zone117x** [comment] 2021-01-20 11:55
@wileyj thanks, I looked at that one, then some others that integrate with Express. Looking through this one https://www.npmjs.com/package/express-prom-bundle
I see
> Let's say you want to have latency statistics by URL path, e.g. separate metrics for /my-app/user/, /products/by-category etc.
> 
> Just taking req.path as a label value won't work as IDs are often part of the URL, like /user/12352/profile. So what we actually need is a path template. The module tries to figure out what parts of the path are values or IDs, and what is an actual path. The example mentioned before would be normalized to /user/#val/profile and that will become the value for the label. These conversions are handled by normalizePath function.

This sounds like the exact problem the current lib is facing, right?

**Comment by wileyj** [comment] 2021-01-20 14:58
definitely seems like it. the main goal from my perspective is to reduce the number of paths that are reported as individual paths. 
from above, if we take the path `/extended/v1/address/<address>/transactions`,  using a template we should be able to reduce all the addresses in that path to something like `/extended/v1/address/<address_val>/transactions`.

I have no preference on what the template looks like. if we want to reduce all paths to their root, or more fine-grained - as long as the end result is we concat all similar paths into a single metric, where the only path change is the address being requested.

**Comment by zone117x** [comment] 2021-01-21 13:31
Express's extensibility must make this a difficult problem. All paths are already defined in a way where Express knows the "path template" values, .e.g.
https://github.com/blockstack/stacks-blockchain-api/blob/cba956ef75656689db855e6538408e3aec33b42b/src/api/routes/address.ts#L108
Yet the prom express middleware libs don't take advantage of this. The one I linked previously uses heuristics to convert a raw url to a templated path, which won't work for most of ours because a STX address won't be detected. 

Aiming to have something figured out today or tomorrow.

**Comment by wileyj** [comment] 2021-03-10 16:08
@zone117x still seeing a LOT of metrics being returned for paths in particular. 
Last count was 166K, a lot of them for paths dealing with accounts and transactions. 
```
http_requests_total{method="get",path="/v2/accounts/STHTWPGNH6Q9KX04K42PGR6XQD1FTJR4Q5BGE6XR",status_code="200"} 6
http_requests_total{method="get",path="/v2/contracts/source/ST1JSH2FPE8BWNTP228YZ1AZZ0HE0064PS54Q30F0/pool-registry",status_code="200"} 9
```

would it be possible to add these to buckets like `/v2/accounts/:account` or some other *catch-all* to reduce the amount of paths here?
There is a second question that I'm not sure if there is a good answer to:
we have a lot of web scrapers for things like `/php-admin` which returns a **404**. Would it make sense to add all 404's to a single bucket? I'm not inclined to think so, but wondering if you have any ideas if there is a way to handle those.

**Comment by zone117x** [comment] 2021-03-10 18:04
Sure. The API isn't really aware of the v2 paths, but it could add custom rules for it. I'm not a fan of maintaining all these duplicate route definitions, but not sure what other choice we have. /cc @kantai

**Comment by kantai** [comment] 2021-03-11 20:49
Is it possible to just add a catch all rule for the paths forwarded to the `stacks-node`s? The `stacks-node` itself has its own prometheus metrics.

**Comment by CharlieC3** [comment] 2021-03-16 19:06
> Is it possible to just add a catch all rule for the paths forwarded to the `stacks-node`s? The `stacks-node` itself has its own prometheus metrics.

@kantai Until [this issue](https://github.com/blockstack/stacks-blockchain/issues/1818) is resolved for stacks-blockchain, the stacks-node metrics probably won't be able to replace what some of the API metrics are exposing through Nginx. The closest metric we have related to stacks-node API endpoints is `stacks_node_rpc_requests_total`, which doesn't separate by endpoint nor expose latency. So condensing these stacks-node-api metrics into a single catch-all will result in a large loss of operational knowledge.

cc @zone117x

**Comment by kantai** [comment] 2021-03-16 20:08
I see -- is there another option until #1818 is resolved (which should be the plan long term-- any nodes _not_ servicing API instances are missing out on these metrics as is)? When you say we're getting data from Nginx, is that data impacted by PR #502 (that seems like it's just updating the application's prom metrics, not the nginx instance)? If not, we should be able to configure the Nginx prometheus metrics to perform some pattern matching to reduce the number of path metrics without just losing all the insights we could be getting.

**Comment by CharlieC3** [comment] 2021-03-16 20:13
> any nodes not servicing API instances are missing out on these metrics as is

Yes, because their traffic isn't going through Nginx.

> When you say we're getting data from Nginx, is that data impacted by PR #502 (that seems like it's just updating the application's prom metrics, not the nginx instance)? 

This isn't clear to me either, but @wileyj's comment in this issue's description:
> We had a similar issue with the legacy explorer that was handled like this:
> https://github.com/blockstack/blockstack-explorer/blob/master/server/index.js#L24-L37

makes me think the Nginx metrics collected can be influenced by downstream services. @wileyj can you confirm or explain how this works?

**Comment by wileyj** [comment] 2021-03-17 14:23
> makes me think the Nginx metrics collected can be influenced by downstream services. @wileyj can you confirm or explain how this works?

this works as you would imagine - if the proxied service is slow, the nginx metrics will show that. 
in this case, if the `/metrics` endpoint is taking too long to complete, it has had an impact on other requests due to CPU used to serve the request. as a result, nginx metrics show a definite spike in latency for all traffic. 

I would argue that most operational knowledge isn't useful for retaining all paths proxied to a stacks-node. 
most of the paths are only called a handful of times at most.

**Comment by CharlieC3** [comment] 2021-03-17 14:31
> I would argue that most operational knowledge isn't useful for retaining all paths proxied to a stacks-node.
most of the paths are only called a handful of times at most.

I don't think you'll find any disagreements there, but lumping all requests into a single bucket would result in a large loss of useful knowledge. We've already found that being able to distinguish certain paths from others, like `/v2/pox`, has been useful to understand bottlenecks in the service.

Ideally, we would come up with a list of some API endpoints we deem useful and group relevant requests into those buckets .

**Comment by wileyj** [comment] 2021-03-17 14:56
`/v2/pox`, `/v2/info` etc are already separate. These are the main ones where we'd see issues from something like the wallet.

**Closed** 2021-03-17 16:30 UTC
Labels: P2
