### ISSUE TITLE
Disappearing Mempool TX

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain-api#333] opened 2020-11-16 15:49 UTC
@aulneau reported this on Discord:

https://stacks-node-api.blockstack.org/extended/v1/tx/0xbe9d516a51def18c167c5949863a327f76baa9f8f1855f8cd1515b28bec64353 is pending and then not available and then shows up as confirmed (if it follows what I have been seeing).
This is the general behavior of what I have seen:
- tx shows up as pending
- data refreshes (polling every 2.5 seconds in the explorer)
- tx is no longer pending, can't find it at all
- once tx is confirmed, shows up again

This isn't a data fetching issue with the explorer, the API itself isn't returning the pending tx once it has vanished

**Comment by zone117x** [comment] 2020-11-16 15:56
This appears to be a bug in how the sidecar's mempool DB pruning work during re-orgs. At the moment, a mined canonical tx will trigger the deletion of the associated mempool tx. During re-orgs that revert that canonical tx, there is not a corresponding "restoration" of moving the tx back into the mempool.

**Comment by zone117x** [comment] 2020-11-17 16:41
This appears to still be still happening. Re-investing.

**Comment by zone117x** [comment] 2020-11-18 22:52
Should be fixed now, cannot reproduce behavior since https://github.com/blockstack/stacks-blockchain-api/pull/341 was deployed.

Problem appears to have been a dangling sql `COMMIT`. Although still low confidence in how that fixed this particular bug..

**Closed by zone117x** 2020-11-18 22:52 UTC
