### ISSUE TITLE
Support GET for total and locked balances per address

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-blockchain-api#437] opened 2021-02-09 12:14 UTC
Currently the API only returns the total _unlocked_ per address whereas it needs to support locked and unlocked amounts as well (e.g. for integration into the explorer per https://github.com/blockstack/explorer/issues/362).

The API should return separate values per address for:

- Total balance (locked plus unlocked)
- Unlocked balance
- Locked balance

**Comment by markmhx** [comment] 2021-02-09 12:21
@agraebe Is this a task you'd be able to help us execute over the coming weeks from the DevX end? Or should @andresgalante start thinking about how we might be able to tackle it on the UserX side given our engineering resources?

**Comment by agraebe** [comment] 2021-02-09 15:04
@zone117x please chime in here with your thoughts 🙏

**Comment by zone117x** [comment] 2021-02-15 14:37
@markmhx it looks like this was solved on the explorer's side? I still think we need this in the API, but is this still an urgent priority? Ideally I'd like to wait until the v1-genesis data import code in the `bns` branch is ready to extend before working on this.

**Comment by zone117x** [comment] 2021-02-15 14:46
Also, I think we can close this as essentially a dupe of https://github.com/blockstack/stacks-blockchain-api/issues/423
(this issue describes the API endpoint request, but the original issue more accurate describes what needs to be done)

**Comment by markmhx** [comment] 2021-02-16 12:07
@zone117x We'll need this to support the display of total, unlocked and locked balances in the wallet per https://github.com/blockstack/stacks-wallet/issues/453, though you're correct that this is already resolved in the explorer.

It's not super urgent but we may be looking to develop the above wallet functionality in the coming days. Is the work for "v1-genesis data import code in the bns branch" something expected to take much longer?

**Closed** 2021-02-16 12:08 UTC
